
let actionTypes = {

 RESULTS_CORRECT: "RESULTS_CORRECT",
 RESULTS_INCORRECT: "RESULTS_INCORRECT",
 RESULTS_NO_PENALTY: "RESULTS_NO_PENALTY",
 RESULTS_RESET: "RESULTS_RESET",
 SET_LIVE_RESULTS: "SET_LIVE_RESULTS",
 RESET_LIVE_RESULTS: "RESET_LIVE_RESULTS",
 SET_FINAL_RESULTS: "SET_FINAL_RESULTS"
}

export default actionTypes;
