
let actionTypes = {

 RESULTS_CORRECT: "RESULTS_CORRECT",
 RESULTS_INCORRECT: "RESULTS_INCORRECT",
 RESULTS_NO_PENALTY: "RESULTS_NO_PENALTY",
 RESULTS_RESET: "RESULTS_RESET",
 SET_LIVE_RESULTS: "SET_LIVE_RESULTS",
 RESET_LIVE_RESULTS: "RESET_LIVE_RESULTS",
 SET_FINAL_RESULTS: "SET_FINAL_RESULTS",
//  from <App/>
 HINTS_VISIBILITY: "HINTS_VISIBILITY",
 RESULTS_VISIBILITY: "RESULTS_VISIBILITY",
 TIMER_VALUE: "TIMER_VALUE",
 CONSTANT_TIMER_VALUE: "CONSTANT_TIMER_VALUE",
 COUNTER_RUNNING: "COUNTER_RUNNING",
 TOGGLE_ACTIVE: "TOGGLE_ACTIVE",
TO_RESET: "TO_RESET",
 DISPLAY_TO_RESET: "DISPLAY_TO_RESET",
// passing as props from <App/> to <Fetch/>
  MY_TEXT: "MY_TEXT",
  WIKI_TITLE: "WIKI_TITLE",
  RANDOM_ARTICLE: "RANDOM_ARTICLE",
  // passing as props from <App/> to  <Reducer> -> <Display/>
  INDEX_OF_PARTIAL_TEXTARR: "INDEX_OF_PARTIAL_TEXTARR",
  // from <Display/>
  TEXT_AREA_VALUE: "TEXT_AREA_VALUE",
  COLOR_FOR_EACH_LETTER: "COLOR_FOR_EACH_LETTER",




}

export default actionTypes;
